# VARIABLES Y FUNCIONES

Python como lenguaje de programaciòn ofrece muchas ventajas en comparacion a otros lenguajes, y una de ellas es que **es un lenguaje legible e intuitivo.** Es decir que no tiene por qué parecer lenguaje extraterrestre para cualquier programador inexperto e incluso para cualquier persona que no sepa de programación en lo absoluto. 
En esta clase se va a explorar un poco el concepto de variable, como se declaran y usan de manera adecuada. Además se abordará el tema del uso de librerias y sus respectivas funciones en conjunto con las variables definidas.

## VARIABLES

Una variable es un espacio que se asigna en la memoria para determinar el valor de un tokken que se especifica por el programador, por ejemplo:

In [1]:
# la variable A se define con el valor 5
A = 5
#la variable B se define con el valor 12.6
B = 12.6
#la variable C se define como el producto de A y B , es decir el producto de 5 y 12.6
C = A * B
# la variable D se define como la diferencia entre C y A ponderada por el valor de B 
D = (C-A)/B
# se imprimen las variables en orden (A,B,C,D)
print( A )
print( B )  
print( C )
print( D )

5
12.6
63.0
4.603174603174604


In [2]:
# cabe aclarar que 'print()' es una funcion que imrpime en consola lo que le entra por parametro entre parentesis
#esto sirve sea uno o muchos argumentos, separados por comas.
print("A = ",A )
print("B = ",B )
print("C = ",C )
print("D = ",D )
print ("Todas = ",A,B,C,D)

A =  5
B =  12.6
C =  63.0
D =  4.603174603174604
Todas =  5 12.6 63.0 4.603174603174604


**[GP]** Comentar el código **describiendo lo que se hace** es, a mi parecer, la única Good Practice que no es un consejo amistoso sino un **deber como programador**, experto o inexperto. Comentar el código le permite a otra persona que lea el codigo tener mayor facilidad de **entender el proceso** que se esta haciendo. Cuando uno programa con regularidad, muchas veces es necesario consultar código que se hizo en el pasado y la mayoría de las veces sucede que uno ya no está familiarizado con el proceso que se ejecuta. Comentar el código le permite a un "futuro Yo" vovler a entender el código después de haberlo casi que olvidado. 


Las variables no solo se pueden crear sino tambien editar, permitiendo cambiar el valor de estas durante el desarrollo del codigo:

In [3]:
A = 1/1000 
C= A * B  # despues de cambiar el valor de A se vuelve a computar A * B, que en el caso anterior daba 63.
print(C)

0.0126


In [4]:
A = 10 
print(A)

#el valor de A se puede re definir en terminos de su antiguo valor. esto aplica para cualquier tipo de variable.

A = 3*A
print(A)

10
30


Hasta el momento se han tratado variables numericas, no obstante existen diferentes tipos de variable:

In [5]:
variable1 = 10 #valor entero (int)
variable2 = 55.54  #valor decimal (float)
variable3 = 55.123143534242352345543665454523545 #valor decimal con doble espacio para cifras decimales (double)
variable4 = True #variable logica true o False (boolean)
variable5 = "Hola" #cadena de caracteres o texto (string)
variable6 = 1+1j #valor complejo con unidad real e imaginaria (complex)

#propiedades entre tipos de  variable
print(variable2+variable6) #valor complejo sumado a valor real decimal
print(variable4+variable3) #valor logico  o booleano sumado a valor decimal (en base numerica True = 1 y False = 0)
print(variable4) #valor booleano
print(variable5*variable1) # string multiplicado por un entero

(56.54+1j)
56.12314353424235
True
HolaHolaHolaHolaHolaHolaHolaHolaHolaHola


**[GP]** Es siempre buena idea ponerle nombres descriptivos a las variables. Esto sirve a la hora de leer el código despues de mucho tiempo o mostrarselo a alguien más ya que facilita el asociar la variable con su respectiva funcionalidad. Así, si la variable corresponde a un precio , es prudente llamarla "precio" o algo relacionado.

**[GP]** Usualmente las variables **NO** se nombran con mayúsculas. No hay ningún tipo de problema en hacerlo, solo es más facil escribir código cuando todas las letras son minusculas.

### Tipos
Como se puede ver, las variables en python pueden venir de diferentes formas. Esto implica que python necesita cierta jerarquia para la operación de variables. Para ello, existe el concepto de *Tipo* que hace referencia a la clase a la que pertenece al variable. Aunque hay diferentes Tipos de variable en python, los más básicos son:

In [6]:
#type() permite saber el tipo de la variable que se esta tratando

print(type(variable1))
print(type(variable2))
print(type(variable3)) # lee esta variable como float , pero la idea es que sea reconocida como dobule
print(type(variable4))
print(type(variable5))
print(type(variable6))

<class 'int'>
<class 'float'>
<class 'float'>
<class 'bool'>
<class 'str'>
<class 'complex'>


### Castings y Converisones de Tipo
Muchas veces se requiere que python admita solo determinado Tipo de variable en una función o incluso que un resultado venga en un tipo específico. Para solucionar este dilema se puede hacer una *Conversion de Tipo* (en tanto sea posible) haciendo uso de *funciones constructoras*:   

In [7]:
variable_float = 2.8
variable_int = 10
variable_string = "35"

floatToInt = int(variable_float) #conversion de float a int
intToFloat = float(variable_int)#conversion de int a float
intToComp = complex(variable_int)#conversion de int a complex
stringToInt = int(variable_string)

print(variable_float,"era de tipo",type(variable_float),"pero ahora es ",floatToInt," de tipo ",type(floatToInt))
print(variable_int,"era de tipo",type(variable_int),"pero ahora es ",intToComp," de tipo ",type(intToComp))
print(variable_int,"era de tipo",type(variable_int),"pero ahora es ",intToFloat," de tipo ",type(intToFloat))
print(variable_string,"era de tipo",type(variable_string),"pero ahora es ",stringToInt," de tipo ",type(stringToInt))

2.8 era de tipo <class 'float'> pero ahora es  2  de tipo  <class 'int'>
10 era de tipo <class 'int'> pero ahora es  (10+0j)  de tipo  <class 'complex'>
10 era de tipo <class 'int'> pero ahora es  10.0  de tipo  <class 'float'>
35 era de tipo <class 'str'> pero ahora es  35  de tipo  <class 'int'>


#### OPERACIONES BÁSICAS

Python tiene incorporado por defecto un conjunto de **operaciones matemáticas** entre variables de las cuales ya hemos visto algunos ejemplos. Con el avance del *manual* se verán más formas de **tansformar** cantidades al igual que funciones que Python también tiene incorporadas, pero por el momento es necesario tener esto en cuenta:

In [8]:
A = 10
B = 3   #definiendo variables para ilustrar mi punto

In [9]:
print("Suma",A+B)
print("Resta",A-B)
print("Multiplicacion",A*B)
print("Division",A/B)
print("Modulo o Residuo",A%B) 
print("Division entera", A//B)
print("Exponenciacion",A**B)


Suma 13
Resta 7
Multiplicacion 30
Division 3.3333333333333335
Modulo o Residuo 1
Division entera 3
Exponenciacion 1000


## Listas, Tuplas y Diccionarios
Cuando se trata ya no de una sino de varias variables que se quieren manejar existen algunas estructuras de datos que pueden ser útiles. 


### Listas
Las listas son contenedores ordenados de datos que no son fijos, es decir que son mutables, y que adicionalmente permite duplicados. Para declarar una lista, se peude usar la definición manual o por constructor:

In [10]:
#creacion de lista por definicion manual
por_comprar = ["Leche","Huevos","Mantequilla","Naranjas","Sal","Pimienta","Azucar","Detergente","Arroz"]
print(por_comprar) #se crea la lista y ahora se imprime

['Leche', 'Huevos', 'Mantequilla', 'Naranjas', 'Sal', 'Pimienta', 'Azucar', 'Detergente', 'Arroz']


Las listas almacenan información de forma ordenada y se puede acceder a ella con los *indices* de la lista:

In [11]:
print(por_comprar[0]) #para accesar alguna posicion de la lista solo basta usar su indice en corchetes cuadrados
print(por_comprar[3]) #es importante recordar que el indice comienza desde 0 siendo este la primera posicion

Leche
Naranjas


In [12]:
#se pueden seleccionar varios elementos consecutivos de la lista con un corte o slice
print(por_comprar[1:5]) #En este caso se hace un slice desde  el indice 1 (incluyendole) hasta el 5(sin incluirlo).
                        #esto es: las posiciones 2,3,4,5 pero no la sexta.

['Huevos', 'Mantequilla', 'Naranjas', 'Sal']


In [13]:
print(por_comprar[:]) #esto imprime la lista de principio a fin, la ausencia del valor de inicio se interpreta 
#como el indice 0 y asi mismo la ausencia del valor de fin se interpreta como el ultimo indice

['Leche', 'Huevos', 'Mantequilla', 'Naranjas', 'Sal', 'Pimienta', 'Azucar', 'Detergente', 'Arroz']


In [14]:
print(por_comprar[::2]) #esto imprime la lista cada 2 valores comenzando desde el 0

['Leche', 'Mantequilla', 'Sal', 'Azucar', 'Arroz']


In [15]:
print(por_comprar[2:6:3]) #esto imprime la lista comenzando en el indice 2 hasta el 6 en pasos de a 3 elementos

['Mantequilla', 'Pimienta']


In [16]:
 #los indices negativos corresponden a posiciones desde el final de la lista
print(por_comprar[-1])#ultima posicion
print(por_comprar[-2])#penultima posicion
print(por_comprar[:-2]) #toda la lista hasta el antepenultimo elemento
print(por_comprar[::-2]) #toda la lista desde el final en pasos de a dos hacia atras

Arroz
Detergente
['Leche', 'Huevos', 'Mantequilla', 'Naranjas', 'Sal', 'Pimienta', 'Azucar']
['Arroz', 'Azucar', 'Sal', 'Mantequilla', 'Leche']


Las listas son elementos **mutables** lo que quiere decir que una vez creadas pueden ser alteradas al igual que sus elementos.

In [17]:
por_comprar.append("Shampoo") #'append' adiciona un item al final de la ista
print(por_comprar) 

['Leche', 'Huevos', 'Mantequilla', 'Naranjas', 'Sal', 'Pimienta', 'Azucar', 'Detergente', 'Arroz', 'Shampoo']


In [18]:
por_comprar.insert(3,"Harina") #'insert' adiciona el elemento indicado en el inidice proporcionado
#se adiciona Harina en el indice 3
print(por_comprar)

['Leche', 'Huevos', 'Mantequilla', 'Harina', 'Naranjas', 'Sal', 'Pimienta', 'Azucar', 'Detergente', 'Arroz', 'Shampoo']


In [19]:
por_comprar.reverse() #usar el metodo 'reverse' invierte el orden de la lista
print(por_comprar)

['Shampoo', 'Arroz', 'Detergente', 'Azucar', 'Pimienta', 'Sal', 'Naranjas', 'Harina', 'Mantequilla', 'Huevos', 'Leche']


In [20]:
por_comprar.sort() #usar el metodo 'sort' organiza la lista (san valores numericos o cadenas de caracteres)
print(por_comprar)

por_comprar.sort(reverse=True) # Tambien se puede organizar de forma descendiente
print(por_comprar)

['Arroz', 'Azucar', 'Detergente', 'Harina', 'Huevos', 'Leche', 'Mantequilla', 'Naranjas', 'Pimienta', 'Sal', 'Shampoo']
['Shampoo', 'Sal', 'Pimienta', 'Naranjas', 'Mantequilla', 'Leche', 'Huevos', 'Harina', 'Detergente', 'Azucar', 'Arroz']


Tambien se pueden remover elementos de la lsita:

In [21]:
print(por_comprar)
por_comprar.remove("Shampoo")
por_comprar.remove("Naranjas")
por_comprar.remove("Harina")
print(por_comprar)

['Shampoo', 'Sal', 'Pimienta', 'Naranjas', 'Mantequilla', 'Leche', 'Huevos', 'Harina', 'Detergente', 'Azucar', 'Arroz']
['Sal', 'Pimienta', 'Mantequilla', 'Leche', 'Huevos', 'Detergente', 'Azucar', 'Arroz']


In [22]:
print(por_comprar)
del por_comprar[2] #elimina la tercera posicion de la lista
print(por_comprar)

['Sal', 'Pimienta', 'Mantequilla', 'Leche', 'Huevos', 'Detergente', 'Azucar', 'Arroz']
['Sal', 'Pimienta', 'Leche', 'Huevos', 'Detergente', 'Azucar', 'Arroz']



**CONTINUANDO . . .** para crear una lista usando el constructor:

In [23]:
por_comprar = list()  #se usa el constructor de la clase lista
por_comprar.append("Queso") 
por_comprar.append("Leche") 
por_comprar.append("Yogurt")  #se adicionan tres elementos

por_comprar  #cuando se imprime la lista con print() no retorna ningun valor , solo lo muestra.
                #al llamar la lista si se espera un valor retornado, por ende esta celda tendria un valor out.


['Queso', 'Leche', 'Yogurt']

**IMPORTANTE** tener en cuenta que en ningun momento se puso una restricción sobre el contenido de la lista:

In [24]:
por_comprar=["Leche" , 25 , True , 5+1j , 'a' ,3.54] #se puede tener todo tipo de variable en una lista
por_comprar

['Leche', 25, True, (5+1j), 'a', 3.54]

**Bastante conveniente ¿no?** viendo ya que se puede tener *cualquier* variable dentro de una lista, y ya que las listas **tambien son variables**...

**¿Eso no da lugar a ideas macabras?**

In [25]:
lista1 = ["Perro","Gato","Colibri"]
lista2 = [2.23 , 3.45 , 1.37]   # se crean tres listas de prueba
lista3 = [True , False , True]

lista_de_listas = [lista1 , lista2 , lista3] # se hace una lista cuyos elementos son las tres listas

lista_de_listas

[['Perro', 'Gato', 'Colibri'], [2.23, 3.45, 1.37], [True, False, True]]

Al tener una estructura contenedora **A** dentro de otra estructura **B** se dice que **A** está anidada dentro de **B**, O generalmente se usa el verbo en inglés *nested*. Si usted también tiene esa curiosidad innata por saber que más sucede, de seguro se preguntó cómo acceder a los valores que estan en las listas anidadas. Pero si me ha llevado el ritmo de seguro sabe la respuesta a ello:

In [26]:
lista_de_listas[0][1]  #de la primera lista (indice 0) retorne su segundo valor (indice 1)

'Gato'

**RECUERDE** que esto sucede porque *lista_de_listas[0]* es una variable que corresponde a ["Perro","Gato","Colibri"] y el anexo [1] consulta la segunda posición de dicha lista.

**BONUS :** Las cadenas de caracteres o *strings* pueden ser interpretados como una lista de caracteres.

In [27]:
texto = "Agujeros negros electricamente cargados que giran rápidamente revolviendo el espaciotiempo a su alrededor."
#los espacios vacios tambien son un caracter
print(texto[16:30])
print(texto[::3])

electricamente
Ajonr eran rd einádeeeleolsctm saed.


### Diccionarios
Cuando se tiene información organizada **y etiquetada** es facil aceeder a ella usando diccionarios. Estos son estructuras contenedoras que permiten la asignación de una etiqueta al dato almacenado, lo que permite buscar información de manera ordenada. En la creación de un diccionario se debe definir la etiqueta o *key* y posteriormente su valor asociado. En el proximo ejemplo se tiene una lista compras y los precios en dolares:

In [28]:
#definicion de un diccionario
por_comprar = {"Leche":1.25,"Huevos":0.75,"Mantequilla":2.05,"Naranjas":1.50}

print(por_comprar)

{'Leche': 1.25, 'Huevos': 0.75, 'Mantequilla': 2.05, 'Naranjas': 1.5}


Como se puede observar a cada elemento le corresponde un precio. Para acceder a la información del deccionario basta con: 

In [29]:
por_comprar["Leche"]

1.25

In [30]:
por_comprar["Huevos"]

0.75

La información tambien puede ser cambiada si se requiere:

In [31]:
por_comprar["Huevos"]=0.50
print(por_comprar)

{'Leche': 1.25, 'Huevos': 0.5, 'Mantequilla': 2.05, 'Naranjas': 1.5}


**Ahora**, ¿Qué sucederá si se intenta cambiar el valor de un *key* que no existe dentro del diccionario? Lo esperado sería que se lanzara un error.

In [32]:
por_comprar["Manzanas"]=1.75

**¿Qué sucedió?** No se lanzó ningún error. Miremos que le pasó al diccionario:

In [33]:
por_comprar

{'Leche': 1.25,
 'Huevos': 0.5,
 'Mantequilla': 2.05,
 'Naranjas': 1.5,
 'Manzanas': 1.75}

¿Astuto no? Definir el valor de un *key* inexistente **actualiza el diccionario** agregando el nuevo elemento. Al igual que con las listas, no hay problema al definir diferentes tipos de variables dentro del diccionario:

In [34]:
diccionario_prueba = {"lista":[1,2,3,4] ,
                     "entero":5 ,
                     "float":2.56 ,   #cuando se esta definiendo una estructura, no debe ser todo en una
                     "string":"hola mundo",#sola linea. Tambien se puede hacer salto de linea despues de las comas.
                     "dict":{"valor A":1,"valor B":20}}#y por qué no, un diccionario anidado.... 
diccionario_prueba

{'lista': [1, 2, 3, 4],
 'entero': 5,
 'float': 2.56,
 'string': 'hola mundo',
 'dict': {'valor A': 1, 'valor B': 20}}

**[GP]** Cuando se esta definiendo una estructura contenedora muy grande, es mejor visto hacer estos saltos de linea para no tener lineas demasiado largas y dificiles de editar.

In [35]:
diccionario_prueba["dict"]["valor B"]=diccionario_prueba["lista"]

¿Puede inferir que sucedio en esta última linea de código? veamos que sucedió: 

In [36]:
diccionario_prueba

{'lista': [1, 2, 3, 4],
 'entero': 5,
 'float': 2.56,
 'string': 'hola mundo',
 'dict': {'valor A': 1, 'valor B': [1, 2, 3, 4]}}

In [37]:
diccionario_prueba["dict"]["valor B"][3]

4

Sustitui el valor de "valor B" en el diccionario "dict" con la lista almacenada en "lista". Se pueden hacer estructuras de distintos niveles que organizen la información. Como acabe de mostrarle, se puede tener una lista en un diccionario . . . en otro diccioanrio.   

## LIBRERIAS Y FUNCIONES

Para poder acceder a más funcionalidades, y así desbloquear el potencial completo de python, es necesario aprender un poco sobre qué son las funciones y las librerías. Estas herramientas nos permitiran hacer calculos más complejos si necesidad de escribir el proceso todas las veces que lo necesitemos o tener que construir funciones super complejas a partir de operaciones sencillas.

### Funciones
Una función es un bloque compacto de código que **solo se ejecuta cuando es llamado por otra parte del código**. A la función ingresan unas variables (o ninguna) llamadas *Parámetros* y puede retornar una, varias o ninguna.Las funciones tienen nombre por el cual se les llama.

Para definir una función se usa la expresión **def** seguida del nombre de la función y entre parentesis los nombres de los posibles parámetros esperados. Por ejemplo, a continuación se mustra una función que recibe como parámetro el radio de un circulo y retorna el valor de su circunferencia:
 



In [38]:
def circunferencia(radio):
    pi = 3.141592   #SE definE pi manualmente DENTRO DE LA FUNCION
    circ = 2*pi*radio #Calculo de la circunferencia
    return circ #se retorna el valor calculado

Note que a pesar de haber definido la función y haber ejecutado la celda de código **no pasó nada**. Esto es porque ninguna parte del código la ha llamado. 
También es importante resaltar la **indentación**: Que las tres últimas lineas estén tabuladas a la derecha implica que estas perteneces a la función definida en la primera linea. En python la indentación de cierta forma simboliza que las lineas indentadas son *subordinadas* de la ultima linea con menor indentación que en este caso sería la primera. Ahora revisemos si la función sirve:

In [39]:
circunferencia(10) #circunferencia de un circulo de radio = 10

62.83184

Otro aspecto importante es la localidad de la variable *pi*. Si bien fue definida dentro de la función circunferencia y esa fue ejecutada ya, esto pasa cuando queremos revisar el valor de pi:

In [40]:
pi

NameError: name 'pi' is not defined

Este error sucede porque pi es una variable definida **localmente** dentro de la función *circunferencia()* y solo está definida dentro de esta. Por otra parte, si hacemos esto:

In [41]:
pi = 3.141592 # En esta ocasión se define pi por fuera de la funcion 
def circunferencia(radio):
   
    circ = 2*pi*radio #Calculo de la circunferencia
    return circ #se retorna el valor calculado

In [42]:
circunferencia(10)

62.83184

In [43]:
pi

3.141592

Ahora, ya que *pi* fue definido por fuera de la función, la localidad de la variable se ve anulada. Otros ejemplos de funciones son:

In [44]:
def funcionA(a,b):
    return 2*a - b  #sean cuales sean los valores a y b, funcionA retornara el doble de a menos b
funcionA(10,2) # 2*10-2 = 18 

18

**NOTE** que la funcion "funcionA" recibe dos valores como parámetros de entrada. **¿Cómo sabe la función cual es cual?**  Con el orden basta. El primer valor se asigna al primer parámetro, el segundo valro de entrada al segundo parámetro y asi sucesivamente para funciones con más parámetros. Otra forma que no depende del orden es simplemente asignar los valores por el nombre del parámetro (si se conoce):

In [45]:
funcionA(b=2,a=10)

18

**[GP]** Es mejor usar los nombres de los parámetros para definir sus valores. Esto evita confusiones y posibles errores malinterpretando el orden de los párametros. También cuando se re-lee el código es mejor ya que no es necesario buscar la definición de la función para saber en que orden van los parámetros o revisar a que corresponden dentro de la función.


También es posible tener funciones que no dependen de **ningún parámetro de entrada**:

In [46]:
valor = 1
def funcionB(): # WOW no hay parámetro
    print(2*valor) # imprime el doble de la variable valor, sin retornar nada

funcionB()
valor = 50
funcionB()

2
100


In [47]:
def funcionC(a):
    return 2*a-1 #funcion aburrida

def funcionD(a):
    return 3*a+1 #funcion aburrida

def funcionCD(a,b):
    return funcionC(a)+funcionD(b) #funcion aburr... no del todo. Las funciones tambien llaman otras funciones!
funcionCD(1,2) #(2*1-1) + (3*2+1) = 1 + 7 = 8

8

**¿Más ideas macabras?** Note que una función (CD) puede llamar a otra (C y D) y usar el valor que retorna **siempre y cuando la función de apoyo esté definida**. Y ya que la función general, que en este caso es CD, ya está definida...

Para mostrarle a donde quiero llegar es necesario esperar a la siguiente clase de este capítulo, en el anexo *'Recursividad'*. Por el momento tenga fresca y presente la idea que se nos acaba de ocurrir.




### Funciones incorporadas
Antes mencioné que Python tenía unas operaciones matemáticas incorporadas por defecto al igual que unas **funciones**. a continuación mostraré algunas de las más útiles.

In [48]:
pow(3,2) #otra forma de exponenciacion , en este caso es 3 a la potencia de 2

9

Para saber la longitud de un contenedor se usa la función **'len'** que retorna un entero correspondiente a la longitud del arreglo. **Importante** notar que la longitud es absoluta, es decir que si hay 4 elementos en el contenedor entonces retorna el valor 4, y no se guia por el indice del arreglo (que iria de 0  a 3).

In [49]:
lista_prueba=[-3,-2,-1,0,1,2,3] #lista de prueba
inventario = {"leche":3,"Mangos":4,"frijoles":10,"aguacate":7} 


print("la longitud de la lista es " , len(lista_prueba) )   # 'len' da la longitud de un contenedor
print("la longitud del inventario es ", len(inventario) )

la longitud de la lista es  7
la longitud del inventario es  4


Una función muy útil para transformar contenedores es **'map'** que asigna los valores de un arreglo a otro haciendo uso de una función que entra por parámetro, es decir que aplica la función a cada elemento del arreglo.

In [50]:
def duplicar(n):
    return 2*n

lista_duplicada = map(duplicar,lista_prueba)

print(lista_duplicada)

¿Qué? ¿Qué significa este resultado tan criptico? Bueno, es que la función map no retorna un contenedor como tal. Para que sea un contenedor debe ser de la clase 'list' o 'dict' si es lista o diccionario respectivamente, pero este objeto es de la clase 'map' y corresponde al mapeo que se hace de cada valor con la función dada. También se trata de un contenedor solo que en este caso es más abtracto y no se puede representar como una secuencia de numeros en un contenedor. Para obtener los valores del nuevo arreglo se usa una conversion de tipo:

In [51]:
lista_nueva = list(lista_duplicada)

print(lista_nueva)

[-6, -4, -2, 0, 2, 4, 6]


##### Factorial

La función factorial de un numero entero corresponde a la multiplicación de todos los enteros menores o iguales a dicho numero y mayores a cero. Se denota con un signo de exclamación al lado del numero entero en cuestión. Es decir,

$5! = 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1  = 120$ 

También, 

$0! = 1$

En este orden de ideas, una forma de mostrar la función general es:

 $n! = \prod_{n}^{i = 1} i$

Si se detiene a mirar bien la función factorial, en particular el caso de $5!$, es facil notar que:

$5! = 5 \cdot 4! = 5 \cdot 4 \cdot 3! =$. . .

A este tipo de funciones que se pueden definir respecto a si mismas se les llama **funciones recursivas** y en programación suponen una herramienta demasiado poderosa: **La recursividad**. 

Continuando con el ejemplo de la función factorial 

### Librerias
Una de las grandes ventajas de python es la diversidad de sus funcionalidades y el gran apoyo por parte de la comunidad en cuanto a la creación de nuevas herramientas y librerias. Pero ¿Qué es una librería? En simples términos *es un paquete de funciones, variables y clases que satisfacen determinado proceso  o funcionalidad*.

La librería más básica en python es **numpy** que contiene utilidades para el tratamiento de cantidades numéricas. Finalmente podemos comenzar con la diversión...

Para usar una librería es necesario importarla al código **antes** de usarla. Esto se hace con el comando **'import'**. Al importar la libreria se le puede asignar un pseudonimo con el fin de abreviar el nombre cada vez que se use. Estos e hace con el comando **'as'**:

In [52]:
import numpy as np     # aca le asigné a la libreria numpy el pseudónimo np al momento de importarla 

**[GP]** Ya que las librerias suelen usarse varias veces en el código y técnicamente esto puede ser en cualquier parte del código, es prudente importar las librerias que se vayan a usar desde el pricnipio del código. de esta forma se puede usar cualquier elemento de la libreria en cualquier parte del código.

**[GP]** A la librería *numpy* generalmente se le asigna el pseudónimo 'np'. Claro, una persona puede ponerle otro pseudónimo a numpy como 'npy','num','jorge' o como lo desee, pero personalmente la gente que hace eso me da asco. Otro grupo de programadores prefiere solo importar la libreria 
```python
import numpy
``` 
y llamar el nombre 'numpy' cada vez que la usan, pero bueno, con eso si soy indiferente. 


Python tiene un conjunto de librerías descargadas por defecto, numpy entre ellas, y cuando se quieren usar solo hace falta importarlas y ya está. Otras librerias más experimentales, específicas o en desarrollo por la comunidad requieren ser **descargadas o instaladas manualmente** ya que python **no** está programado para descargarlas al momento de instalarse en el computador.

Tambien se puede importar solo una parte de la libreria con el fin de ahorrar memoria al momento de correr el codigo:

In [53]:
from numpy import linalg as lng

En esta ocasión se importó de *numpy* un conjunto de funcionalidades utiles para el álgebra lineal llamado 'linalg' (que veremos más adelante). También se importó con un pseudonimo. *NO* se importó toda la librería de numpy, sino solo la parte que nos interesaba.

Una de las grandes ventajas de Python como lenguaje de programación es la facilidad con la que se lee el código. La interpretabilidad que ofrece permite que lineas de código como la de arriba parezcan más una oración de un texto que un trozo de código para informática.

### Leve introducción a numpy

Numpy es una libreria cuyo objetivo principal es el tratamiento de cantidades numericas con operaciones matemáticas del mundo moderno. A continuación mostraré algunas funcionalidades que tiene, sin embargo la mayoria de ellas se irán mostrando más adelante en el desarrollo de clases posteriores del manual.

#### Arrays, vectores o arreglos

En numpy se tiene una nueva clase de contendor, en este caso si está restringido a valores numericos en general: enteros, decimales o complejos. El Arreglo de numpy es editable pero de tamaño fijo , es decir que sus valores pueden ser cambiados , sin embargo no se pueden tener más o menos elementos en el vector.

In [54]:
lista_prueba = [1,2,3,4,6]

array_lista = np.array(lista_prueba)

# asi es, se peude crear un vector a partir de una lista de valores

print(array_lista)


array_lista[4] = 5 # y se puede editar

print(array_lista)

[1 2 3 4 6]
[1 2 3 4 5]


In [55]:
#tambien puedo vovler un array una lista
lista_back = list(array_lista)
lista_back

[1, 2, 3, 4, 5]

#### Más dimensiones , Rick . . .
¿Qué sucede en matemáticas cuando tengo un vector de vectores? Claro! una matriz.

In [56]:
matriz = [[1,2,3],[4,5,6],[7,8,9]] # se comienza con una lista de listas

matriz = np.array(matriz) #redefino matriz como un array de si mismo 

matriz # et voilá! tenemos una matriz! 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
print("como listas = ",matriz[2][1])
#al igual que con las listas, se pueden consultar valores viendolo como una lista anidada dentr de otra


# pero tambien se pueden consultar como una coordenada de la matriz (tercera fila, segunda columna)
print("como matriz = ",matriz[2,1])

como listas =  8
como matriz =  8


In [58]:
matriz[ 1: , :-1 ] #toda la matriz, excepto la ultima columna y la primera fila

array([[4, 5],
       [7, 8]])

In [59]:
matriz[:,1] # todos los valores de la segunda columna

array([2, 5, 8])

In [60]:
#con el comando .T se puede transponer un elemento lineal, como la matriz
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

##### ceros y unos
Se pueden crear automáticamente vectores de cualquier tamaño con solo ceros o unos en cada valor. Son más útiles de lo que uno pensaría.

In [61]:
array_cero = np.zeros(10) #array de ceros con 20 elementos
array_uno = np.ones(10) #array de unos con 20 elementos


print(array_cero)
print(array_uno)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [62]:
np.ones([5,5]) #genera una matriz de 5x5 de unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Diferencias
Pero . . . ya habiendo visto las listas, se preguntará, ¿En qué se diferencia un array de una lista? ¿No es más sencillo solo dejar la lista creada y ya? Bueno, es que el array puede ser interpretado como un Vector matemático, con todos los beneficios que ello trae:

In [63]:
lista_doble = 2 * lista_prueba #multiplico la lista por 2
array_doble = 2 * array_lista #multiplico el array por 2


print("lista doble = ",lista_doble)
print("array doble = ",array_doble)
print("array doble +1 = ",array_doble + 1)
print("lista doble +1 = ",lista_doble+1)

lista doble =  [1, 2, 3, 4, 6, 1, 2, 3, 4, 6]
array doble =  [ 2  4  6  8 10]
array doble +1 =  [ 3  5  7  9 11]


TypeError: can only concatenate list (not "int") to list

Como vemos la lista es tan incomoda matemáticamente hablando que hasta lanzó un error cuando intenté sumarle un numero. Los arrays en general son las estructuras predilectas para hacer  operaciones matemáticas. Las listas son más útiles como formas de almacenar información , pero no para procesarla. 

In [64]:
4 * matriz #estas propiedades se extienden a matrices, eventualmente

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

#### Linspace

Cuando uno desea geenrar un espacion lineal de valores, con N valores distribuidos en intervalos iguales entre numeros A y B se usa **'linspace'** para generarlos automáticamente: 

In [65]:
valores = np.linspace(2,4,5) # quiero generar 5 numeros igualmente distribuidos entre 2 y 4
print(valores)  #notese que linspace retorna un array de valores

[2.  2.5 3.  3.5 4. ]


#### Valores aleatorios
Un buen lenguaje de programación siempre tiene una forma de generar valores aleatorios. En este caso numpy ofrece una variedad de posibilidades para esta tarea con uno de sus paquetes : numpy.random

la función **'random'** genera un numero aleatorio entre 0  y 1

In [66]:
np.random.random()  # esta funcion genera un numero aleatorio entre 0  y 1

0.8067919630796608

In [67]:
np.random.random([2,3]) # se le puede suministrar un arreglo con las dimensiones de una matriz y retorna una matriz

array([[0.69352422, 0.32524815, 0.99293407],
       [0.78085255, 0.25262048, 0.91332957]])

Para generar numeros enteros aleatorios se usa **'randint'**

In [68]:
np.random.randint(10,20) # randint retorna un valor entero aleatorio entre los dos valores proporcionados

14

In [69]:
np.random.randint(10,20,[10,3]) # tambien recibe un argumento adicional para la forma del arreglo de salida

array([[15, 13, 13],
       [19, 18, 14],
       [11, 19, 16],
       [11, 19, 17],
       [13, 17, 10],
       [18, 17, 15],
       [15, 10, 10],
       [14, 18, 19],
       [17, 17, 15],
       [18, 19, 10]])

La función **'normal'**  genera un numero aleatorio dentro de una distribucion normal o Gaussiana. Si no se le proporcionan parametros, genera el numero aleatorio de una distribucion gaussiana ceentrda en 0 y con desviación standard de 1 ($\mu = 0$ , $\sigma = 1$)

In [70]:
np.random.normal()

-0.27560564088439526

In [71]:
np.random.normal(10,5) #le ingresan como parametros el centro de la distribucion y la desviacion(mu = 10, sigma =5)

9.02013074832749

In [72]:
np.random.normal(10,5,[3,3]) #de nuevo, la forma ....

array([[ 8.41552402, 11.7010232 ,  9.57068709],
       [ 2.65087587, 17.54022563,  8.98722703],
       [ 9.07959272,  9.00148204,  5.86083873]])

La función **'uniform'** sirve para generar numeros aleatorios en una distribución uniforme. Se comporta similar a **'random'** solo que esta vez le ingresan como parametros los valores limites de la distribución.

In [73]:
np.random.uniform(-5,5,[3,3]) #genera una matriz de 3 x 3 con valores aleatorios entre -5 y 5

array([[ 2.47344658, -0.39821985,  0.83958101],
       [ 2.27437061, -2.50223938,  0.54273573],
       [ 0.16465541, -2.15529385, -1.05455294]])

#### Funciones matemáticas
Numpy tiene un conjunto de funciones que son familiares a cualquiera que haya tenido una formación básica en matemáticas. De la misma forma, tiene constantes que ayudan al proceso de cálculo en muchas de ellas.

In [74]:
np.pi # tiene una definicion decente de pi, no como la que hice en la funcion circunferencia

3.141592653589793

In [75]:
np.sqrt(100) # raiz cuadrada

10.0

In [76]:
np.log10(100) #logaritmo base 10

2.0

In [77]:
np.log2(16) #logaritmo base 2

4.0

In [78]:
np.log(np.e) #logaritmo natural o neperiano. Tambien tiene definida la constante de Euler (e) 

1.0

Ya que tiene incorporado el valor de pi, ¿por qué no tendría todo el paquete de operaciones trigonométricas?

In [79]:
np.sin(0) # funcion seno (calculo en radianes)

0.0

In [80]:
np.sin( np.pi/2 )

1.0

In [81]:
np.cos(np.pi/2) # y la funcion coseno tambien está

6.123233995736766e-17

In [82]:
print(np.arccos(1)) # funcion inversa de coseno, se espera 0 como resultado
print(np.arcsin(1)) # funcion inversa de seno, se espera  pi/2 (1.57...) como resultado

0.0
1.5707963267948966


Esto que sucedio con la función coseno es posible que pase de vez en cuando y es necesario tener un poco de 'criterio científico' para dicernir si se trata de un error. En este caso, coseno de $\frac{\pi}{2}$ es igual a 0, pero la respuesta que se recibe **NO** es cero. Pero a pesar de ser distint0 de cero, el resultado es un valor bastante cercano. 

Python no es perfecto y trabaja con cierta precisión numerica  (mas o menos 16 decimales de precision), este tipo de 'desatinos' por lo general no representan un inconveniente y recae sobre el programador determinar si decide ver ese resultado como un cero o no.

In [83]:
np.tan(np.pi/2)  #tangente tambien esta disponible.
#Aunque de tangente de pi/2 se espera una indeterminacion a infinito(o algo cercano)

1.633123935319537e+16

Python muchas veces en lugar de dar indeterminacions a infinito retorna valores muy grandes, a pesar de que tiene su propioa definición de infinito.

In [84]:
np.inf #definicion de infinito de numpy

inf

In [85]:
100/np.inf #dividamos algo ente infinito

0.0

In [86]:
np.arctan(np.inf) #funcion inversa de tangente, de nuevo se espera pi/2 (1.57..)

1.5707963267948966

Otra ventaja de numpy es que permite aplicar funciones sobre sus vectores:

In [87]:
numeros = np.linspace(0,np.pi*2,10) #10 numeros entre 0 y 2*pi distribuidos de manera uniforme

coseno = np.cos(numeros) #coseno para todos

print(coseno)

[ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]


#### Algo de estadistica
Cuando se tratan muchos numeros, en ocasiones se quieren obtener datos sobre su distribución y sobre el conjunto en general. Para ello numpy tiene algunas funciones para determinar estadisticos de arreglos:

In [88]:
array_prueba = np.random.uniform(-10,10,100) #100 numeros entre -10 y 10

In [89]:
np.mean(array_prueba) # retorna el promedio del parametro de entrada , sea lista o array

0.6041697556668927

In [90]:
np.median(array_prueba) # mediana del arreglo

0.8916024659336044

In [91]:
np.std(array_prueba)# desviacion standard

5.9721958227824405

In [92]:
np.var(array_prueba) #varianza

35.66712294566003

In [93]:
np.amax(array_prueba) # maximo valor del arreglo

9.98091336173417

In [94]:
np.amin(array_prueba) #valor minimo

-9.932910513866357

In [95]:
np.argmax(array_prueba) # la POSICION o INDICE del maximo valor


95

In [96]:
np.argmin(array_prueba) # la POSICION o INDICE del minimo valor

13

In [97]:
np.arange(1,20,3) # genera un arreglo de enteros entre 1 y 20 dando pasos de a 3 numeros

array([ 1,  4,  7, 10, 13, 16, 19])

In [98]:
np.arange(20,10,-2) #tambien se puede hacia atras, en este caso de 20 a 10 en pasos hacia atras de 2 numeros

array([20, 18, 16, 14, 12])

#### Where ...?
La función **'where'** permite buscar las posiciones de elementos dentro del arreglo que cumplen con determinadas condiciones. 

In [99]:
array_prueba = np.random.uniform(10,30,80)
array_prueba

array([14.85967305, 19.4226324 , 10.25634335, 17.61997445, 20.21260393,
       27.13017982, 24.42411867, 19.24891631, 21.63255682, 16.37494142,
       14.07408471, 12.35223545, 23.39185168, 24.70702802, 27.42256629,
       22.1969361 , 24.54231987, 25.31199489, 10.6838358 , 10.40272868,
       12.8927233 , 28.79280649, 23.67149503, 17.58933817, 13.95860773,
       14.78200452, 18.71995772, 12.05248821, 12.6554569 , 15.55552361,
       20.6420821 , 13.13840986, 28.91914778, 26.11877687, 14.77569914,
       24.79134273, 16.75165674, 11.77211752, 25.55563736, 17.08471338,
       29.60088509, 25.63440317, 12.87786266, 12.92144209, 10.45197746,
       12.14488679, 19.97709859, 27.0599166 , 16.55932046, 12.72783633,
       24.73171052, 27.55424889, 24.3549522 , 16.54671841, 10.86511671,
       29.40354869, 27.14797733, 22.14584456, 22.12182057, 12.55349594,
       15.66218772, 12.30345004, 25.68510188, 12.29239613, 18.05712719,
       20.65952343, 13.4165498 , 25.04376949, 18.51610017, 14.69

In [100]:
indices = np.where(array_prueba > 20) #quiero saber las posiciones donde los valores son mayores a 150
indices

(array([ 4,  5,  6,  8, 12, 13, 14, 15, 16, 17, 21, 22, 30, 32, 33, 35, 38,
        40, 41, 47, 50, 51, 52, 55, 56, 57, 58, 62, 65, 67, 70, 71]),)

Si lo nota bien, esto retorna un arreglo las posiciones donde se cumple la condición x > 20. Pero lo retorna como un array donde su primer elemento es la lista de indices, pero tiene un misterioso segundo elemento vacio. Por ello solo vamos a tomar ese primer elemento:

In [101]:
indices = indices[0] # solo tomando el primer elemento correspondiente a los inidices

array_prueba[indices] #miremos que hay en los inidices que solicitamos...

array([20.21260393, 27.13017982, 24.42411867, 21.63255682, 23.39185168,
       24.70702802, 27.42256629, 22.1969361 , 24.54231987, 25.31199489,
       28.79280649, 23.67149503, 20.6420821 , 28.91914778, 26.11877687,
       24.79134273, 25.55563736, 29.60088509, 25.63440317, 27.0599166 ,
       24.73171052, 27.55424889, 24.3549522 , 29.40354869, 27.14797733,
       22.14584456, 22.12182057, 25.68510188, 20.65952343, 25.04376949,
       29.1628953 , 25.62723143])

En efecto, encontramos valores superiores a 20.

## RESUMEN

* **Variables** son todas aquellas asignaciones en la memoria del computador que corresponden a elementos que se desean guardar. La declaración de variables es la base de la programación en python y entender su comportamiento es escencial para seguir con lecciones posteriores.


* Existen variables denominadas **Contenedoras** que sirven para estructurar, jerarquizar y ordenar otras variables. Usar con destreza estas variables permite la creación de redes de información complejas como bases de datos y clases, que se tocarán más adelante.


* Las **Funciones** son otro pilar de la programación en python, puesto que permiten realizar transformaciones en variables o extraer información del código. Estas funciones son trozos de código que solo se ejecuta si se llama directamente. Estas funciones pueden llamar otras funciones o como veremos más adelante, también se pueden llamar a si mismas.


* Las **Librerías** sirven para ahorrar código programando al usar funciones,variables y clases que alguien más ya programó y que pueden ser útiles para el trabajo de otros. Son paquetes funcionales cuyo objetivo es facilitar algún proceso en específico.


* Librerías como **Numpy** son usadas con frecuencia en la programación por las herramientas que ofrecen. Numpy en particular ofrece funciones y constantes utiles para cualquier cálculo matemático. La cantidad de librerias que hay para python es absurda, en este manual trataremos muchas de las escenciales, pero no estaremos ni cerca de tratarlas todas. Por el momento solo es necesario tener presente que si se requiere hace una tarea compleja o un calculo absurdo, posiblemente python ya tenga una solución para ese problema.

## EJERCICIOS

La base de todo aprendizaje es implementar lo aprendido. Para aplicar lo aprendido en esta clase puede realizar los ejercicios correspondientes a la clase 1 de la hoja de ejercicios. 