   # LÓGICA Y LOOPS

Ya que hablamos un poco de estructuras organizadas de información (como los vectores y las listas) y de el uso de funciones, surgen necesidades que no se pueden satisafecer con lo que se ha aprendido hasta el momento. Python tiene herramientas para solucionar problemas que , como veremos, surgen a partir de necesidades más complejas de los programadores. Herramientas que sirven para hacer recorridos largos de forma automática o definir condiciones en el desarrollo de un proceso.

### Lógica
Es de esperarse que la programación tenga lógica, sobre todo cuando la computación está fundamentanda en esta. En lo que a python concierne, se usa el concepto de [**Álgebra de Boole**](https://es.wikipedia.org/wiki/%C3%81lgebra_de_Boole) o **Lógica Booleana**. Esta no es más que un esquema matemático para definir la lógica de operadores y compuertas en computación.

En el contexto del programador inexperto, la logica boolana corresponde a la interpretanción de cualquier enunciado que pueda ser reducido a Verdadero (**True**) o Falso (**False**). Estos son valores que ya hemos visto antes en el curso y que corresponden a variables de tipo *boolean*. Para poner un ejemplo, miremos que pasa en python cuando en vez de hacer operaciones tratamos de comparar elementos o hacer afirmaciones:

In [1]:
1>2      # 1 mayor que 2

False

In [2]:
500 < 5*10 # 500 menor que 5*10 = 50

False

In [3]:
100 > 10 # 100 mayor que 10

True

Acá se presentan los operadores *mayor que* (>) y *menor que* (<) siendo usados en **afirmaciones lógicas** que son respondidas con un valor booleano. Al expresar afirmaciones falsas, el valor retornado es *False* y de igual forma al presentar afirmaciones ciertas el valor respuesta es *True*. 

existen mas operadores lógicos, enter ellos:

In [4]:
100 == 200  #100 es igual a 200

False

In [5]:
100 == 10*10 #100 = 10*10

True

In [6]:
300 >= 50*10  #300 mayor o igual que 50*10

False

In [7]:
300 <= 301 #300 menor o igual a 301 

True

In [8]:
100 != 200 #100 diferente a 200

True

En cada uno de estos casos se está evaluando un solo enunciado, es decir, solo se evalua una **condición**. pero ¿Qué pasa si se quiere evaluar más de un enunciado? y si se pudiera evaluar más de uno ... ¿Cómo se *mezclaría* la condición de verdad de cada una para determinar la condición de verdad deseada?

Introduciendo otros operadores lógicos: **or**   y   **and**.

#### OR lógico
OR, como su traducción del inglés lo indica, se refiere al *condicional que es cierto si almenos uno de sus elementos es cierto*, es decir que es cierto *si y solo si* alguno de los enunciados que le conforma es cierto. 

Un ejemplo de la vida cotidiana es: *"Comer manzanas o peras me hace feliz"*. Mi *Felicidad* hipotética es válidad si recibo manzanas **O** peras. Es válida si almenos una es cierta. 

En términos más ... computacionales:

In [9]:
(100 > 200) or (50 > 100) #100 mayor que 200 O 50 mayor que 100 (ambas son falsas)

False

In [10]:
(100 > 200) or (500 == 5*100) #100 mayor que 200 O 500 igual que 5*100  (una verdadera una falsa)

True

In [11]:
100 == 10*10 or 4<10 # 100 igual que 10*10 o 4 menor que 10 (ambas verdaderas)

True

**[GP]** si bien los parentesis rodeando cada enunciado no son necesarios, es mejor tenerlos para organización del código y evitar futuras confusiones. 

La *compuerta lógica* OR tambien puede ser expresada con una línea vertical:

In [12]:
(100 > 200) | (500 == 5*100) #100 mayor que 200 O 500 igual que 5*100  (una verdadera una falsa)

True

**IMPORTANTE** recordar que los valores booleanos pueden ser representados en notación binaria y viceversa con conversores de tipo.

In [13]:
bool(0) #valor booleano de 0

False

In [14]:
bool(1) #valor booleano de 1

True

In [15]:
int(True) #valor entero de True

1

In [16]:
int(False) #valor entero de False

0

#### AND lógico
A diferencia de OR, AND se refiere al *condicional que es cierto si todos sus elementos son ciertos*, es decir que es cierto *si y solo si* todos los enunciados que le conforman son ciertos.

Ejemplo: *"Comer manzanas y peras me hace feliz"*. Mi Felicidad hipotética es válidad si recibo manzanas Y peras. Es válida si las dos son ciertas.

In [17]:
(100 > 200) or (50 > 100) #100 mayor que 200 Y 50 mayor que 100 (ambas son falsas)

False

In [18]:
(100 > 200) and (500 == 5*100) #100 mayor que 200 Y 500 igual que 5*100  (una verdadera una falsa)

False

In [19]:
100 == 10*10 and 4<10 # 100 igual que 10*10 Y 4 menor que 10 (ambas verdaderas)

True

La compuerta lógica AND también puede ser expresada con un '&':

In [20]:
(100 == 10*10) & (4<10)

True

#### Comprobando más enunciados
No solo enunciados de comparación entre cantidades se pueden comprobar, también está permitido hacer más afirmaciones que pueden ser verificadas como verdaderas  o no:

In [21]:
lista_rock = ["Iggy Pop","Axel Rose","Jim Morrison","Jimmy Hendrix"] #lista de prueba

In [22]:
"Iggy Pop" in lista_rock #Iggy está en la lista

True

**¿Qué cree usted que le pregunté a Python?** En efecto! verifiqué que un elemento existiera dentro de la lista. Esta es una herramienta que más adelante nos será de utilidad. El comando **in** se refiere a la existencia de un elemento dentro de un *iterable*, que por el momento lo tomaremos en cuenta como un elemento con un numero **contable** de valores. Las listas, arreglos, diccionarios y los elemnto de tipo *map* son ejemplos de iterables.

In [23]:
"Kurt Cobain" in lista_rock #Kurt no está en la lista

False

In [24]:
dict_elementos = {"Hidrogeno":1, "Helio":2, "Litio":3, "Berilio":4, "Boro":5} #dicionario de elementos

In [25]:
"Boro" in dict_elementos #Boro es un elemento en el diccionario

True

In [26]:
2 in dict_elementos #a pesar de que 2 es un valor asociado a un elemento del diccionario
#no es un elemento de diccionario en si mismo

False

Otro enunciado a comprobar es afirmar el tipo de una variable:

In [27]:
type(5) is int #se introuce la afirmacion is

True

In [28]:
type(5)==int #que al parecer....es equivalente a ==

True

La afirmación **is** implica que dos elementos apuntan al mismo objeto en memoria. **==** implica que dos valores son iguales. Recordemos la notación de slices que vimos al introducir las listas:

In [29]:
lista_A = [2,4,6,8] #se define la lista A
lista_B = lista_A   #La lista B se define como la misma list A
lista_C = lista_A[:] #la lista C se define como un slice de principio a fin de la lista A


es decir que la lista C se define como una lista **diferente** (una copia) a la lista A, a pesar de tener los mismos valores:

In [30]:
print(lista_A)
print(lista_B)
print(lista_C)

[2, 4, 6, 8]
[2, 4, 6, 8]
[2, 4, 6, 8]


In [31]:
lista_A is lista_B

True

In [32]:
lista_A == lista_B

True

En el caso de la lista B que se define como la misma lista A ambos enunciados son equivalentes. Ahora vemaos que pasa con la lista C:

In [33]:
lista_A is lista_C

False

In [34]:
lista_A == lista_C

True

**RECORDAR** que al hacer slices se crean **copias parciales** de la lista que se *corta*. Esto implica que se crea un nuevo objeto en memoria incluso si se copia *toda* la lista como en este caso. Es importante tener en cuenta cuándo esto sucede puesto que muchas veces definir una variable como igual a otra hace que se refiera al mismo objeto en memoria , como las listas A y B. Esto a veces trae problemas: si se quiere modificar la lista B, es psoible que se modifique la lista A puesto que se trata del mismo objeto. mientras que al modificar la lista C solo modifica a esta ya que es un pbjeto diferente. 

#### NOT lógico
Los enunciados lógicos también se pueden negar, y para ello esta el operador lógico **not**, cuya única función es negar el enunciado en cuestión.

In [35]:
not True

False

In [36]:
a = 5
b = 10

a > b  # a es mayor a b, es decir 5 > 10 (Falso)

False

In [37]:
not a > b   # negar 5 > 10

True

### Condicionales

Como su nombre lo indica los **condicionales** verifican el cumplimiento de una condición para desarrollar una parte específica del proceso. En el caso de la programación,  se verifica la validez *(True or False)* para un enunciado, y de cumplirse se procede con un proceso subordinado.

#### sentencia IF   o    IF statement
Este tipo de condicional **segrega** un bloque de cigo como proceso subordinado y lo ejecuta **si y solo si** la condicion establecida se cumple. 

Ejemplo cotidiano: *"Si me demoro en salir de casa, voy a perder el bus"*. El evento de *perder el bus* depende unicamente del condicional *demorarse en salir de casa*. Si perdí el bus es porque me demoré en salir,y así mismo, si me demoré en salir entonces voy perder el bus.

Para usar el condicional *"if"* se escribe la palabra if, seguida de la condicion a cumplirse. El código subordinado se escribe a partir de la linea siguiente y todo el bloque **con indentación** puesto que es precisamentre subordinado:

In [38]:
#se escribe la condicion, se finaliza con DOS PUNTOS para cerrar la sentencia IF
if(4 < 5):  #  4 es menor a 5
    print("4 es menor a 5") # si la condicion se cumple , se imprime el mensaje

4 es menor a 5


In [39]:
#se escribe la condicion, se finaliza con DOS PUNTOS para cerrar la sentencia IF
# se puede omitir el parentesis
if 4 > 5:  #  4 es mayor a 5
    print("4 es mayor a 5") # si la condicion se cumple , se imprime el mensaje

Como se puede observar, el código subordinado (en este caso se trata del print) se ejecuta unicamente si se cumple la condición.

**[GP]** Es mejor usar los parentesis en la declaración de la sentencia para conservar el orden. como veremos en breve, las afirmaciones condicionales pueden se compuestas y conservar el orden de operaciones en estos caso es más complejo sin usar parentesis. Estos permiten delimitar cada enunciado por aparte y facilitar la interpretación.

**IMPORTANTE** NO olvidar los dos puntos al final de la sentencia e indentar las lineas de códio subordinado. Tambien es prudente notar que escribir en python es casi como escribir ordenes en inglés. La interpretabilidad del código en Python es un regalo del Dios de cada religión.

Tambien puede existir el caso de *"nested if's"*:

In [40]:
lista_prueba = [2,4,6,8,0]

if(2 in lista_prueba):
    #los siguientes 2 if estan subordinados al if de la linea anterior (note la indentacion hacia la derecha)
    if(4 in lista_prueba):
        print("estan 2 y 4") #esta linea esta subordinada al if de 4, que a su vez esta subordinado al if de 2
    if(3 in lista_prueba):
        #este if NO esta subordinado al if de 4, pero si al de 2. el de 4 y 3 estan al mismo nivel
        print("estan 2 y 3")

estan 2 y 4


Para que el código subordinado del IF se ejecute, basta con que su condición sea cierta, incluso si esta es compuesta:

In [41]:
if ( 100 == 10*10 and 6 in lista_prueba): # 100 = 10*10 y 6 en lista_prueba
    print("ambas se cumplen!")

ambas se cumplen!


In [42]:
if(4<2 or 0 in lista_prueba): #4 menor a 2 o 0 en lista_prueba
    print("alguna se cumle!")

alguna se cumle!


Veamos un enuncaido compuesto más complejo:

In [43]:
if ( ( 4 > 2 ) and ((6 in lista_prueba) or (5 in lista_prueba)) ) :
    print("...algo se cumple")

...algo se cumple


#### Y si hay mas casos . . .
¿Qué pasa cuando se quieren evaluar dos o más casos? ¿o que pasa cuando se quiere hacer algo al respecto en caso de no cumplirse la condición? Bueno, para eso se tiene el **else**. Este elemento se usa cuando también se quiere hacer una operación o tarea cuando la condición lógica del *if* no se cumple:

In [44]:
def funcion_A (n):
    if (n < 10):
        print("menor a 10")
    else:
        print("mayor a 10 ")
    

In [45]:
funcion_A(8) # se cumple la condicion del if, entonces se ejecuta el codigo subordinado

menor a 10


In [46]:
funcion_A(19) # NO se cumple la condición del if, entonces se cumple el codigo subordinado de else.

mayor a 10 


La función en cuestión tiene un gran problema que tal vez usted ya ha notado, y es el siguiente:

In [47]:
funcion_A(10)

mayor a 10 


Cuando se le proporciona como parámetro el 10, lo clasifica como mayor a 10 puesto que la condición para ser clasificado como "menor a 10" es sólo que sea menor. Cualquier otro caso (mayor o igual) es clasificado como "mayor a 10". Entonces se tienen dos posibilidades: la primera es hacer un *nested if* :

In [48]:
def funcion_A (n):
    if (n < 10):
        print("menor a 10")
    else:
        if(n == 10):
            print("es 10")
        else:
            print("mayor a 10 ")
    

In [49]:
funcion_A(8)
funcion_A(10)
funcion_A(12)

menor a 10
es 10
mayor a 10 


El *nested if* parce funcionar de maravilla, pero es desordenado para ser una tarea simple. La segunda opción es contraer el *nesting* causado por el *if* subordinado al *else* en lo que se llama un condicional *else if*  o, usando la contracción de python para este enunciado, el condicional **elif**: 

In [50]:
def funcion_A (n):
    if (n < 10): # si n es menor a 10 entonces ... 
        print("menor a 10")
    elif (n==10): # si no se cumple, entonces miremos si es igual a 10 . . . 
        print("es 10")
    else: # y si no se cumple ninguna, pues . , ,
        print("mayor a 10")

In [51]:
funcion_A(8)
funcion_A(10)
funcion_A(12)

menor a 10
es 10
mayor a 10


**IMPORTANTE** tener en cuenta que no se pueden tener *elif* o *else* en el código si que se haya declarado antes un if, ya que estos condicionales son auxiliares al *if* en caso de que este no se cumpla.

Se peuden tener tantos *elif* dependientes en cascada como se desee. 

In [52]:
def funcion_A (n):
    if (n < 10): # si n es menor a 10 entonces ... 
        print("menor a 10")
    elif (n==10): # si no se cumple, entonces miremos si es igual a 10 . . . 
        print("es 10")
    elif(n==12): # si no se han cumplido las anteriores, miremos si es igual a 12...
        print("es 12")
    elif(n==19): # si no se han cumplido las anteriores, miremos si es igual a 19...
        print("es 19")
    else: # y si no se cumple ninguna, pues . , ,
        print("mayor a 10")

In [53]:
funcion_A(8)
funcion_A(10)
funcion_A(12)
funcion_A(19)
funcion_A(22)


menor a 10
es 10
es 12
es 19
mayor a 10


Otro aspecto importante es siempre saber si lo que se quiere es un *elif* o simplemente otro *if*. La diferencia radica en la exclusividad. Cuando se usa *if-elif* se tiene en cuenta que la condición del *elif* se va a evaluar **solamente** cuando las condiciones anteriores han fallado. Si se usa otro *if* este se evaluará independiente de si *if* anteriores han fallado  o no. Por ejemplo :

In [54]:
def funcion_A(n):
    if(n < 10):  #si n es menor a 10
        print("menor a 10")
    elif(2*n < 30): #si no es asi, mirar si el doble de n es menor a 30
        print("doble menor a 30")
    else: #si no se cumple nada, enonces ...
        print("numero grande")
        
def funcion_B(n):
    if(n < 10):  #si n es menor a 10
        print("menor a 10")
    if(2*n < 30): #si el doble de n es menor a 30
        print("doble menor a 30")
    else: #si no se cumple, enonces ...
        print("numero grande")
        
    

In [55]:
funcion_A(8)
funcion_A(12)
funcion_A(18)

menor a 10
doble menor a 30
numero grande


In [56]:
funcion_B(8) # este caso va a pasar por los dos if (n<10 y 2*n<30)
funcion_B(12)
funcion_B(18)

menor a 10
doble menor a 30
doble menor a 30
numero grande


Como se ve, si hay diferencia en usar uno u otro. Esto es importante recalcarlo ya que muchos errores de programador aprendiz vienen por no saber el nivel de **exclusividad** entre condicionales y el nivel de segregación  que se quiere para cada caso a tener en cuenta.

**IMPORTANTE** recordar que las condiciones del *elif* NO tiene que estar necesariamente definidas sobre la misma variable que el *if* al que responden.

#### Función Factorial

La función factorial de un numero entero corresponde a la multiplicación de todos los enteros menores o iguales a dicho numero y mayores a cero. Se denota con un signo de exclamación al lado del numero entero en cuestión. Es decir,

$5! = 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1  = 120$ 

También, 

$0! = 1$

En este orden de ideas, una forma de mostrar la función general es:

 $n! = \prod_{n}^{i = 1} i$

Si se detiene a mirar bien la función factorial, en particular el caso de $5!$, es facil notar que:

$5! = 5 \cdot 4! = 5 \cdot 4 \cdot 3! =$. . .

O, dicho de una manera más formal:

$n! = n \cdot (n-1)!$

A este tipo de funciones que se pueden definir respecto a si mismas se les llama **funciones recursivas** y en programación suponen una herramienta demasiado poderosa: **La recursividad**. 

Continuando con el ejemplo de la función factorial y ya habiendo mencionado en la sección anterior la posibilidad de llamar una función dentro de la función misma, veamos cono esto se puede complementar con la lógica para hacer una función **recursiva** útil. 

In [57]:
def factorial(n):
    if( n == 0):
        return 1  #el factorial de 0 es 1
    else:
        return n * factorial(n-1) # si n es diferente de 0, retorne n por el factorial de (n-1)

Ahora, probemos la función:

In [58]:
print(factorial(0)) # 0! = 1
print(factorial(4)) # 4! = 24
print(factorial(5)) # 0! = 120


1
24
120


### LOOPS

Finalmente es hora de aprender lo que, a mi parecer, es la herramienta más poderosa de python : **Los Loops**.
Esta herramienta ofrece la posibilidad de *iterar* sobre diferentes valores de forma ordenada. ¿Qué quiero decir con 'iterar'? Bueno, se trata de cumplir una funcion varias veces. Una y otra y otra vez.
Al igual que cuando se tratra de lógica, las lineas de código escritas cuando se trata de loops son bastante parecidas a oraciones coherentes en inglés. Esto facilita mucho la tarea de programar al momento de querer formular  sentencias con loops.
Pero, si un loop trata de hace una tarea de forma repetitiva ¿Cuándo se debe detener la iteración? ¿En qué momento se debe parar? Esto depende de **condiciones lógicas** que se definen en la declaración del loop y que **se deben** respetar para seguir iterando. De esto se hablará a profundidad en las siguientes definiciones.


#### While Loop
Como su homonimo en inglés, **while** corresponde a un loop que se seguirá ejecutando **mientras** una condición se cumpla. Como ya se mencionó, estas condiciones son sentencias lógicas que deben ser verdaderas o *True* para que se pueda seguir ejecutando la tarea. Veamos un ejemplo básico:

In [59]:
i =  0   #Variable i

while i<10 : #mientras i siga siendo menor a 10
    print(i)  #imprimir i en cada iteracion
    i = i+1  #y sumarle 1 a i en cada iteracion
    

0
1
2
3
4
5
6
7
8
9


Como vemos, la sentencia *while* se detuvo en el momento en que *i* pasa a ser igual a 10. En ese momento, i ya no cumple la sentencia lógica *i < 10* y el loop se detiene.
Es importante tener en cuenta que el condicional del loop puede usar **cualquier** tipo de sentencia lógica. Un ejemplo un poco más bizarro:

```python
while True:
    print(10)
```
Analice bien lo que estoy tratando de plantearle. La sentencia lógica en este caso se trata de **True** que evidentemente siempre es cierta. Esto implica un loop infinito que haría que se imprimiera en consola el numero 10 por tiempo idefinido. Si quiere intentarlo en su computadora es bajo su propio riesgo.


**Recuerde** que se pueden *matar* procesos desde consola con el comando **Ctrl + C** (Linux)

Otros ejemplos de loop *while* son:

In [60]:
lista_prueba = [0,2,4,6,8,10]
i = 0
#en cada iteracion se aumenta i en uno y se verifica si su doble esta en la lista
while (2*i in lista_prueba):
    print("El doble de ", i , "esta en la lista.")
    i = i+1

El doble de  0 esta en la lista.
El doble de  1 esta en la lista.
El doble de  2 esta en la lista.
El doble de  3 esta en la lista.
El doble de  4 esta en la lista.
El doble de  5 esta en la lista.


In [61]:
i = 0
string_prueba = "El eclipse lunar" 

while ( i < len(string_prueba) ):
    print(string_prueba[i:])
    i=i+1

El eclipse lunar
l eclipse lunar
 eclipse lunar
eclipse lunar
clipse lunar
lipse lunar
ipse lunar
pse lunar
se lunar
e lunar
 lunar
lunar
unar
nar
ar
r


**[GP]** También es conveniente usar parántesis en la condición del loop. De nuevo, se trata de evitar confusiones y mantener un poco el orden dentro del código.

#### For Loop
el loop **for** es un poco más complejo que el loop while puesto que ya tiene su condición para parar incluida en el enunciado. Por lo general se usa para recorrer **iterables** o contenedores de forma ordenada o con cierta lógica. El primer ejemplo útil es poder iterar sobre cantidades numéricas, para ello usaremos el *iterable* **range**:

In [62]:
for i in range(10,15):
    print(i)

10
11
12
13
14


**range** define un espacio de numeros enteros entre el primer argumento (incluyendolo) y el segundo argumento (sin incluirlo). Si el no se asigna el primer valor, se asume como 0:

In [63]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


**IMPORTANTE** recordar que el iterable *range* es de la clase *range* y por ende no es un objeto tan facil de manipular, a menos que se transforma lista o se use con iteradores como *while* o *for*:

In [64]:
print(range(10))

range(0, 10)


In [65]:
print( list(range(10)) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**for** sirve para iterar sobre contenedores o arreglos:

In [66]:
lista_prueba = ["a","b","c","d","e"]

for letra in lista_prueba: #para cada elemento de la lista, se hace ...
    print(letra)

a
b
c
d
e


In [67]:
import numpy as np
espacio_lineal = np.linspace(1,2,15) #espacio lineal de 15 valores distribuidos de 1 a 2
for num in espacio_lineal:
    print(2*num)

2.0
2.142857142857143
2.2857142857142856
2.4285714285714284
2.571428571428571
2.7142857142857144
2.857142857142857
3.0
3.142857142857143
3.2857142857142856
3.4285714285714284
3.571428571428571
3.7142857142857144
3.8571428571428568
4.0


El *for* se puede usar para generar valores basandose en una regla matemática arbitraria, lo cual supone una herramienta enorme a la hora de tratar problemas numericos complejos. También puede ser usada para recorrer arreglos basandose en su indice.

In [68]:
lista_prueba = []

for  i in range(50): #recorre el loop desde 0 (incluyendole) hasta 50 (sin incluirle)
    lista_prueba.append( 3*(i+1)-2) # se le agrega el valor de 3*(i-1) - 2 a la lista para cada i entre 0 y 49

print(lista_prueba)
    

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148]


Los *Loops* también se pueden **anidar** dentro de otros loops, creando *nested loops*. Estos tienen diversos usos, pero los más comunes tienen que ver con **recorrer arreglos, matrices y demás estructuras de datos**:

In [69]:
MAT = np.zeros([5,5]) #matriz de ceros de 5 x 5
print ("ANTES = ")
print(MAT)
for i in range(5): 
    for j in range(5): # el loop sobre j se cumple de 0 a 5 para cada iteracion del loop sobre i
        MAT[i,j] = i+j  #para cada coordenada i,j de la matriz, se asigna el valor i+j
        
print("DESPUES = ")
print(MAT)

ANTES = 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
DESPUES = 
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


## RESUMEN

* Existen formas de *crear, negar, operar y verificar* **enunciados lógicos** en python. Estos enunciados son clave para el desarrollo de un programa y su uso es **ilimitado**.


* **La recursividad, la logica y los Loops** se puede combinar para cumplir funciones más complejas. Con el tiempo ver la *lógica oculta* de programas más sofisticados se hace más facil de ver cuando se conocen los ladrillos con los que estan construidos.


* Los Loops permiten hacer una tarea *repetidas veces* **siempre y cuando se este cumpliendo una condición**. Estos facilitan mucho realizar cálculos sobre listas largas o la generación de nuevos valores basandose en una regla de operación.


* **Los Loops y operaciones lógicas tienen mucho potencial** para crear funciones más potentes que las que se han visto hasta el momento, todo depende de la audacia del programador.

## EJERCICIOS

La base de todo aprendizaje es implementar lo aprendido. Para aplicar lo aprendido en esta clase puede realizar los ejercicios correspondientes a la clase 2 de la [hoja de ejercicios](https://github.com/PaipaPsyche/LearningPython/blob/master/Chapter_1/Ejercicios/Ejercicios_C1.ipynb). 